Repository LDAR-Sim/LDAR_Sim, pull requests merged in 2024-03, with the labels that each got.

#151 Add ability to define Equipment in Site Type File
  LDAR_Sim/src/file_processing/input_processing/emissions_source_processing.py
  LDAR_Sim/src/file_processing/input_processing/infrastructure_processing.py
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/virtual_world/equipment.py
  LDAR_Sim/src/virtual_world/equipment_groups.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/infrastructure_const.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/src/virtual_world/sources.py
Labels: bug, enhancement

#152 V4 add total measured emissions
  LDAR_Sim/src/file_processing/output_processing/multi_simulation_outputs.py
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/virtual_world/emissions.py
Labels: enhancement

#153 <BUG> Account for optional header
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/sites_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/test_activate_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/test_sites_constructor.py
Labels: bug

#154 Add non-repairable emissions functionality
  LDAR_Sim/src/default_parameters/virtual_world_default.yml
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/virtual_world/__init__.py
  LDAR_Sim/src/virtual_world/emissions.py
  LDAR_Sim/src/virtual_world/equipment.py
  LDAR_Sim/src/virtual_world/equipment_groups.py
  LDAR_Sim/src/virtual_world/fugitive_emission.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/infrastructure_const.py
  LDAR_Sim/src/virtual_world/nonfugitive_emissions.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/src/virtual_world/sources.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/nonfugitive_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_activate.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_estimate_start_date.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_expire.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_record_emission.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_update_detection_records.py
Labels: enhancement

#155 V4 mit vs non mit emis
  LDAR_Sim/src/file_processing/output_processing/multi_simulation_outputs.py
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/virtual_world/emissions.py
  LDAR_Sim/src/virtual_world/equipment.py
Labels: enhancement

#156 V4 uncertainty visualizations
  LDAR_Sim/src/file_processing/output_processing/multi_simulation_outputs.py
  LDAR_Sim/src/file_processing/output_processing/multi_simulation_visualizations.py
  LDAR_Sim/src/file_processing/output_processing/output_constants.py
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/file_processing/output_processing/output_visualization_constants.py
  LDAR_Sim/src/file_processing/output_processing/program_specific_visualizations.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_multi_simulation_outputs/test_concat_output_data.py
Labels: enhancement

#159 <FIX> Fix weather usage
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/utils/generic_functions.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/sites.py
Labels: bug

#163 Install guide
  INSTALL_GUIDE.md
  README.md
  USER_MANUAL.md
  changelog.md
  doc-images/image.png
  doc-images/image1.png
  doc-images/image3.png
  doc-images/image4.png
  doc-images/image5.png
  install/.gitmessage
  install/SetupInstructions.md
  install/requirements.txt
  install/requirements_dev.txt
Labels: documentation

#165 fix: prevent type error in site initialization
  LDAR_Sim/src/virtual_world/sites.py
Labels: bug

#161 fix: Improve attribution of measured rates
  LDAR_Sim/src/virtual_world/equipment.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_equipment/test_tag_emissions.py
Labels: bug, enhancement

#162 V4 fix emission duration estimates
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/virtual_world/emissions.py
  LDAR_Sim/src/virtual_world/equipment.py
  LDAR_Sim/src/virtual_world/equipment_groups.py
  LDAR_Sim/src/virtual_world/fugitive_emission.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/nonfugitive_emissions.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/test_calc_est_emis_vol.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/test_estimate_start_date.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/nonfugitive_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_calc_est_emis_vol.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_estimate_start_date.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_record_emission.py
Labels: bug, enhancement
