Repository LDAR-Sim/LDAR_Sim, pull requests merged in 2024-06, with the labels that each got.

#184 <DOC> Virtual world parameter documentation
  USER_MANUAL.md
  doc-images/input_data_structure.png
Labels: documentation

#199 <FEAT>: Add in partial deployment functionality
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/parameters/high_level_parameters.py
  LDAR_Sim/src/scheduling/generic_schedule.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_infrastructure/test_generate_propagating_params.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_infrastructure/test_update_propagating_params.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/sites_testing_fixtures.py
Labels: bug, enhancement

#203 Refactor: Refactor Emissions Structure
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/sensors/default_component_level_sensor.py
  LDAR_Sim/src/sensors/default_equipment_group_level_sensor.py
  LDAR_Sim/src/sensors/default_site_level_sensor.py
  LDAR_Sim/src/virtual_world/component.py
  LDAR_Sim/src/virtual_world/emission_types/__init__.py
  LDAR_Sim/src/virtual_world/emission_types/emission.py
  LDAR_Sim/src/virtual_world/emission_types/non_repairable_emissions.py
  LDAR_Sim/src/virtual_world/emission_types/repairable_emission.py
  LDAR_Sim/src/virtual_world/equipment_groups.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/src/virtual_world/sources.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/equipment_group_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/equipment_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/site_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/emissions_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/test_check_spatial_cov.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_equipment/test_tag_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/non_repairable_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_activate.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_estimate_start_date.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_expire.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_record_emission.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/test_update_detection_records.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/repairable_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_activate.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_calculate_mitigation.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_check_if_repaired.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_estimate_start_date.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_natural_repair.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_tag_leak.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_tagged_today.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/test_update_detection_records.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/sources_testing_resources/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/sources_testing_resources/sources_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_create_emission.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_generate_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_src_contructor.py
Labels: enhancement

#200 <DOCS>V4 virtual world defining files
  LDAR_Sim/src/constants/infrastructure_const.py
  USER_MANUAL.md
Labels: documentation

#205 <FEAT>: Add upfront cost to outputs
  LDAR_Sim/src/file_processing/output_processing/output_utils.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/program.py
  USER_MANUAL.md
Labels: enhancement

#201 <FEAT> V4 stationary method rework
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/default_parameters/m_default.yml
  LDAR_Sim/src/programs/component_level_method.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/scheduling/follow_up_survey_planner.py
  LDAR_Sim/src/scheduling/scheduled_survey_planner.py
  LDAR_Sim/src/scheduling/scheduling_utils.py
  LDAR_Sim/src/scheduling/stationary_schedule.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_survey_site.py
  LDAR_Sim/testing/unit_testing/test_programs/test_site_level_method/test_site_level_method_constructor.py
  LDAR_Sim/testing/unit_testing/test_scheduling/test_survey_planner/test_queue_site_for_survey.py
  LDAR_Sim/testing/unit_testing/test_scheduling/test_survey_planner/test_update_with_latest_survey.py
  USER_MANUAL.md
Labels: enhancement

#204 Intermittent Emissions Functionality
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/virtual_world/component.py
  LDAR_Sim/src/virtual_world/emission_types/__init__.py
  LDAR_Sim/src/virtual_world/emission_types/emission.py
  LDAR_Sim/src/virtual_world/emission_types/intermittency_mixin.py
  LDAR_Sim/src/virtual_world/emission_types/intermittent_non_repairable_emission.py
  LDAR_Sim/src/virtual_world/emission_types/intermittent_repairable_emission.py
  LDAR_Sim/src/virtual_world/sources.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_component/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_component/test_get_detectable_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/emissions_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/intermittent_non_repairable_emission_creation_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/test_activate.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/test_calc_true_emis_vol.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_non_repairable_emission/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/__init__.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/intermittent_repairable_emission_creation_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/test_activate.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/test_calc_true_emis_vol.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/test_get_summary_dict.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_intermittent_repairable_emission/test_update.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_non_repairable_emission/non_repairable_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_repairable_emission/repairable_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/sources_testing_resources/mock_methods.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/sources_testing_resources/sources_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_create_emission.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_generate_emissions.py
Labels: enhancement

#206 <UPD>: Split Default Methods files
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/constants/file_name_constants.py
  LDAR_Sim/src/default_parameters/m_default_mobile.yml
  LDAR_Sim/src/default_parameters/m_default_stationary.yml
  LDAR_Sim/src/file_processing/input_processing/input_manager.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/utils/check_parameter_types.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_site_level_method/test_site_level_method_constructor.py
  USER_MANUAL.md
Labels: enhancement

#207 Quantification update
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/constants/sensor_constants.py
  LDAR_Sim/src/default_parameters/m_default_mobile.yml
  LDAR_Sim/src/default_parameters/m_default_stationary.yml
  LDAR_Sim/src/parameters/parameters_holder.py
  LDAR_Sim/src/programs/component_level_method.py
  LDAR_Sim/src/programs/equipment_group_level_method.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/sensors/METEC_NoWind_sensor.py
  LDAR_Sim/src/sensors/OGI_camera_rk.py
  LDAR_Sim/src/sensors/OGI_camera_zim.py
  LDAR_Sim/src/sensors/default_component_level_sensor.py
  LDAR_Sim/src/sensors/default_equipment_group_level_sensor.py
  LDAR_Sim/src/sensors/default_sensor.py
  LDAR_Sim/src/sensors/default_site_level_sensor.py
  LDAR_Sim/src/sensors/quantification/__init__.py
  LDAR_Sim/src/sensors/quantification/default_quantification_predictor.py
  LDAR_Sim/src/sensors/quantification/uniform_quantification_predictor.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_site_level_method/test_site_level_method_constructor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_default_sensor/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_default_sensor/test_initialize_quantification_predictor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/equipment_group_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_detect_emissions.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_fill_detection_report.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_gen_eqg_survey_report.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_rate_detected.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_sensor_constructor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/equipment_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_detect_emissions.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_fill_detection_report.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_gen_eqg_survey_report.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_rate_detected.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_sensor_constructor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_default_quantification_predictor/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_default_quantification_predictor/test_predict.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_uniform_quantification_predictor/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_uniform_quantification_predictor/test_predict.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/site_level_sensors_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/test_detect_emissions.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/test_fill_detection_report.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/test_rate_detected.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_site_level_sensors/test_sensor_constructor.py
  USER_MANUAL.md
Labels: enhancement

#209 V4 deploy true/false table
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/initialization/initialize_infrastructure.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/utils/prog_method_measured_func.py
  LDAR_Sim/src/virtual_world/infrastructure.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_infrastructure/test_filter_df_by_relevant_method.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_infrastructure/test_populate_tf_site.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_infrastructure/test_set_up_tf_site.py
Labels: enhancement

#210 req: Updated python requirements for V4
  INSTALL_GUIDE.md
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_outputs.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_analysis_results_manager/test_save_sensitivity_variations_mapping.py
  doc-images/image1.png
  doc-images/image4.png
  install/SetupInstructions.md
  install/dev_environment.yml
  install/environment.yml
  install/linux_dev_environment.yml
  install/linux_environment.yml
  install/requirements.txt
  install/requirements_dev.txt
Labels: enhancement

#211 V4 cost outputs
  LDAR_Sim/src/constants/file_name_constants.py
  LDAR_Sim/src/constants/general_const.py
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/default_parameters/outputs_default.yml
  LDAR_Sim/src/file_processing/output_processing/summary_output_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_mapper.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_mapper.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualizations.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_mapper/test_init.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_mapper/test_set_summary_mapping.py
  USER_MANUAL.md
Labels: documentation, enhancement

#212 <DOC>: Cleanup and update documents
  Feature Guides/SetupInstructions.md
  README.md
  USER_MANUAL.md
  changelog.md
Labels: documentation

#208 feat: Add extrapolation to annual emis calcs
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_mapper.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_helpers/test_get_annual_emissions_at_all_sites_with_extrapolation.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_outputs/test_gen_emissions_estimate_summary.py
  USER_MANUAL.md
Labels: enhancement

#215 docs: Add V3 to V4 Parameter Migration Guide
  Guides/Feature Guides/Sensitivity_Analysis.md
  Guides/Version Migration Guides/V2_to_V3_ParameterMigrationGuide.md
  Guides/Version Migration Guides/V3_to_V4_ParameterMigrationGuide.md
  README.md
Labels: documentation

#218 <DOC> Update manual based on new structure
  USER_MANUAL.md
Labels: documentation

#217 fix: moved SetupInstructions.md to Guides folder
  Guides/SetupInstructions.md
Labels: documentation

#225 <UPD>: Update Sensitivity analysis script
  LDAR_Sim/src/ldar_sim_sensitivity_analysis.py
Labels: bug

#223 <ENH>: Remove mitigation plots when no mitigation
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualizations.py
  changelog.md
Labels: enhancement

#231 <FIX> Error message fix
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/programs/method.py
  README.md
Labels: bug

#232 Improve main script
  LDAR_Sim/src/ldar_sim_run.py
Labels: enhancement

#233 fix: Fix bug in metric prefix formatter
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_helpers.py
Labels: bug

#234 <ENH>: Add program visualization options
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/default_parameters/outputs_default.yml
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/ldar_sim.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/ldar_sim_sensitivity_analysis.py
Labels: enhancement
