Repository LDAR-Sim/LDAR_Sim, pull requests merged in 2024-07, with the labels that each got.

#236 fix: Fixed summary output creation failure bug
  LDAR_Sim/src/file_processing/output_processing/summary_output_helpers.py
  changelog.md
Labels: bug

#235 fix: Fix bug with equipment group survey scaling
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/test_sites_constructor.py
Labels: bug

#240 <UPD>: Update default parameter data types
  LDAR_Sim/src/default_parameters/m_default_mobile.yml
  LDAR_Sim/src/default_parameters/m_default_stationary.yml
  LDAR_Sim/src/default_parameters/p_default.yml
  LDAR_Sim/src/default_parameters/virtual_world_default.yml
Labels: bug

#242 Survey time fix
  LDAR_Sim/src/programs/component_level_method.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/scheduling/schedule_dataclasses.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/survey_site_testing_resources.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_deploy_crews.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_get_travel_time.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_survey_site.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/test_get_method_survey_time.py
Labels: bug

#245 fix: Fix error when setting equip properties
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/virtual_world/equipment_groups.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_equipment/test_clean_propagating_parameters_from_equipment_info.py
Labels: bug

#237 Bug fix - Per day costs
  LDAR_Sim/src/programs/component_level_method.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/scheduling/schedule_dataclasses.py
  LDAR_Sim/testing/unit_testing/test_programs/test_component_level_method/__init__.py
  LDAR_Sim/testing/unit_testing/test_programs/test_component_level_method/component_method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_component_level_method/test_deploy_crew_costs_component_method.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_deploy_crew_costs.py
  USER_MANUAL.md
  changelog.md
Labels: bug

#249 feat: Improve Sens Analysis Language Consistency
  Guides/Feature Guides/Sensitivity_Analysis.md
  LDAR_Sim/simulations/simple_test_case1_sens/M_OGI.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/Simulation_settings.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/sens_info.yml
  LDAR_Sim/src/constants/sensitivity_analysis_constants.py
  LDAR_Sim/src/ldar_sim_sensitivity_analysis.py
  LDAR_Sim/src/sensitivity_analysis/parameter_variator.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_results_manager.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_visualizations.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_processing.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_parameter_variator/test_vary_parameter_values.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_processing/test_get_sensitivity_info.py
Labels: enhancement

#254 <FIX>Crew count bugfix
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/testing/unit_testing/test_programs/test_component_level_method/component_method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_estimate_method_crews_required.py
  USER_MANUAL.md
  changelog.md
Labels: bug

#253 <FIX>: Properly update the site list for sites considered for follow-ups and in queue for follow-up
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/scheduling/follow_up_mobile_schedule.py
  changelog.md
Labels: bug

#250 <FEAT>Implement the duration estimation ratio value
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/file_processing/output_processing/program_output.py
  LDAR_Sim/src/file_processing/output_processing/program_output_helpers.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/virtual_world/sites.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/__init__.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_duration_between_dates.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_end_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_end_date_factor.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_factor.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_next_condition.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_prev_condition.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_start_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_calculate_start_date_factor.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_closest_future_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_determine_next_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_determine_prev_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_fixtures_conditions.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_fixtures_end_dates.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_output_helpers/test_fixtures_start_dates.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_outputs/test_calculate_end_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_outputs/test_calculate_start_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_outputs/test_determine_start_and_end_date.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_outputs/test_expand_column.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_program_outputs/test_gen_estimated_fugitive_emissions_to_remove.py
  USER_MANUAL.md
  changelog.md
Labels: documentation, enhancement

#160 Update E2E test suite creator and runner
  LDAR_Sim/testing/end_to_end_testing/e2e_suite_runner.py
  LDAR_Sim/testing/end_to_end_testing/e2e_test_case_creator.py
  LDAR_Sim/testing/end_to_end_testing/test_case_creator/.gitignore
  LDAR_Sim/testing/end_to_end_testing/test_results/.gitignore
  LDAR_Sim/testing/end_to_end_testing/testing_utils/comparison_funcs.py
  LDAR_Sim/testing/end_to_end_testing/testing_utils/result_verification.py
Labels: enhancement

#258 <FIX>: Fix estimated emission to be min.0
  LDAR_Sim/src/file_processing/output_processing/summary_outputs.py
  USER_MANUAL.md
Labels: bug

#263 Initial sites flagging bugfix
  LDAR_Sim/src/programs/site_level_method.py
Labels: bug

#265 fix: Add instructions and support for long paths
  INSTALL_GUIDE.md
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/constants/general_const.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_manager.py
  doc-images/Enable Win 32 long paths.png
  doc-images/Group Policy at Filesystem.png
  doc-images/Windows Run Dialog.png
  doc-images/group policy editor.png
  doc-images/group policy enable long paths.png
Labels: bug

#267 V4 assorted fixes
  INSTALL_GUIDE.md
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/file_processing/input_processing/input_manager.py
  LDAR_Sim/src/virtual_world/sites.py
Labels: bug, enhancement

#268 perf: Improve Survey Results Memory Usage
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/file_processing/output_processing/program_output.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/program.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/scheduling/follow_up_mobile_schedule.py
  LDAR_Sim/src/scheduling/generic_schedule.py
  LDAR_Sim/src/scheduling/schedule_dataclasses.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_group_level_sensors/test_detect_emissions.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_equipment_level_sensors/test_detect_emissions.py
Labels: enhancement

#270 Ldar 41 sampling qe module
  LDAR_Sim/inputs/simple_test_case_1/test_qe.csv
  LDAR_Sim/simulations/simple_test_case1/M_air.yaml
  LDAR_Sim/src/constants/sensor_constants.py
  LDAR_Sim/src/default_parameters/m_default_mobile.yml
  LDAR_Sim/src/file_processing/input_processing/input_manager.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/programs/component_level_method.py
  LDAR_Sim/src/programs/equipment_group_level_method.py
  LDAR_Sim/src/programs/method.py
  LDAR_Sim/src/programs/program.py
  LDAR_Sim/src/programs/site_level_method.py
  LDAR_Sim/src/sensors/METEC_NoWind_sensor.py
  LDAR_Sim/src/sensors/OGI_camera_rk.py
  LDAR_Sim/src/sensors/OGI_camera_zim.py
  LDAR_Sim/src/sensors/default_component_level_sensor.py
  LDAR_Sim/src/sensors/default_equipment_group_level_sensor.py
  LDAR_Sim/src/sensors/default_sensor.py
  LDAR_Sim/src/sensors/default_site_level_sensor.py
  LDAR_Sim/src/sensors/quantification/__init__.py
  LDAR_Sim/src/sensors/quantification/default_quantification_predictor.py
  LDAR_Sim/src/sensors/quantification/sampling_quantification_predictor.py
  LDAR_Sim/src/sensors/quantification/uniform_quantification_predictor.py
  LDAR_Sim/testing/unit_testing/test_programs/test_component_level_method/test_deploy_crew_costs_component_method.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/method_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_deploy_crew_costs.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_deploy_crews.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_estimate_method_crews_required.py
  LDAR_Sim/testing/unit_testing/test_programs/test_method/test_survey_site.py
  LDAR_Sim/testing/unit_testing/test_programs/test_program/test_program_init.py
  LDAR_Sim/testing/unit_testing/test_programs/test_site_level_method/test_site_level_method_constructor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_default_sensor/test_initialize_quantification_predictor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_default_quantification_predictor/test_predict.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_sampling_quantification_predictor/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_sampling_quantification_predictor/test_predict.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_uniform_quantification_predictor/test_predict.py
  USER_MANUAL.md
Labels: documentation, enhancement

#273 QE initialization bugfix
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/sensors/quantification/sampling_quantification_predictor.py
  LDAR_Sim/testing/unit_testing/test_sensors/test_quantification/test_sampling_quantification_predictor/test_set_quantification_errors.py
Labels: bug

#275 <DEL>: Remove generator from end-to-end testing
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_repairable_emissions/inputs/generator/gen_infrastructure.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_repairable_emissions/inputs/generator/gen_infrastructure_emissions_0.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_repairable_emissions/inputs/generator/gen_infrastructure_emissions_1.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_repairable_emissions/inputs/generator/gen_infrastructure_hashes.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4-simple_repairable_emissions/inputs/generator/n_sim_saved.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4_simple_non_repairable_emissions/inputs/generator/gen_infrastructure.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4_simple_non_repairable_emissions/inputs/generator/gen_infrastructure_emissions_0.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4_simple_non_repairable_emissions/inputs/generator/gen_infrastructure_emissions_1.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4_simple_non_repairable_emissions/inputs/generator/gen_infrastructure_hashes.p
  LDAR_Sim/testing/end_to_end_testing/test_suite/V4_simple_non_repairable_emissions/inputs/generator/n_sim_saved.p
Labels: bug

#277 <FIX>: Fixed pre-generate emission dates
  LDAR_Sim/src/virtual_world/sources.py
  LDAR_Sim/testing/unit_testing/test_initialization/test_sources/test_generate_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sources/test_generate_emissions.py
Labels: bug

#278 <ENH>: Remove pregenerated files in script
  LDAR_Sim/testing/end_to_end_testing/e2e_suite_runner.py
  LDAR_Sim/testing/end_to_end_testing/e2e_test_case_creator.py
  LDAR_Sim/testing/end_to_end_testing/testing_utils/remove_generator.py
Labels: enhancement

#280 <DOC>: Update changelog
  changelog.md
Labels: documentation
