Repository LDAR-Sim/LDAR_Sim, pull requests merged in 2024-05, with the labels that each got.

#186 V4 Expiry & Repair date fix
  LDAR_Sim/src/virtual_world/fugitive_emission.py
  LDAR_Sim/src/virtual_world/nonfugitive_emissions.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/fugitive_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/test_natural_repair.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/nonfugitive_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/test_expire.py
Labels: bug

#187 V4 - Mitigation summary outputs
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/constants/param_default_const.py
  LDAR_Sim/src/default_parameters/outputs_default.yml
  LDAR_Sim/src/file_processing/output_processing/program_output_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_output_mapper.py
  LDAR_Sim/src/virtual_world/emissions.py
  LDAR_Sim/src/virtual_world/fugitive_emission.py
  LDAR_Sim/src/virtual_world/nonfugitive_emissions.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_mapper/test_add_yearly_mappings.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_mapper/test_init.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_output_mapper/test_set_summary_mapping.py
  LDAR_Sim/testing/unit_testing/test_file_processing/test_output_processing/test_summary_outputs/test_summarize_program_outputs.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_emissions/emissions_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/fugitive_emission_testing_fixtures.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_fugitive_emission/test_calculate_mitigation.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_nonfugitive_emissions/nonfugitive_emission_testing_fixtures.py
Labels: enhancement

#190 V4 benchmarking script
  .gitignore
  Benchmarking/__init__.py
  LDAR_Sim/src/dev_tools/__init__.py
  LDAR_Sim/src/dev_tools/benchmarking_parser.py
  LDAR_Sim/src/dev_tools/benchmarking_wrapper.py
  LDAR_Sim/src/ldar_sim_run.py
Labels: enhancement

#192 <Fix>: Rework program_output
  LDAR_Sim/src/file_processing/output_processing/program_output.py
  LDAR_Sim/src/file_processing/output_processing/program_output_manager.py
Labels: bug

#193 <FEAT>: Add debug flag
  LDAR_Sim/src/constants/output_messages.py
  LDAR_Sim/src/initialization/args.py
  LDAR_Sim/src/ldar_sim_run.py
Labels: enhancement

#188 feat: Add program mitigation bars visualization
  LDAR_Sim/src/constants/output_file_constants.py
  LDAR_Sim/src/default_parameters/outputs_default.yml
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_helpers.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_mapper.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualizations.py
Labels: enhancement

#196 V4 program params documents
  LDAR_Sim/src/default_parameters/p_default.yml
  USER_MANUAL.md
Labels: documentation

#189 V4 automated sensitivity analysis
  Feature Guides/Sensitivity_Analysis.md
  LDAR_Sim/simulations/simple_test_case1_sens/M_OGI.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/M_OGI2.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/Outputs.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/P_OGI.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/P_none.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/Simulation_settings.yaml
  LDAR_Sim/simulations/simple_test_case1_sens/sens_info.yml
  LDAR_Sim/simulations/simple_test_case1_sens/virtual_world.yaml
  LDAR_Sim/src/constants/error_messages.py
  LDAR_Sim/src/constants/file_processing_const.py
  LDAR_Sim/src/constants/infrastructure_const.py
  LDAR_Sim/src/constants/output_messages.py
  LDAR_Sim/src/constants/sensitivity_analysis_constants.py
  LDAR_Sim/src/file_processing/input_processing/input_manager.py
  LDAR_Sim/src/file_processing/output_processing/summary_visualization_helpers.py
  LDAR_Sim/src/initialization/args.py
  LDAR_Sim/src/ldar_sim_run.py
  LDAR_Sim/src/ldar_sim_sensitivity_analysis.py
  LDAR_Sim/src/parameters/__init__.py
  LDAR_Sim/src/parameters/genric_parameters.py
  LDAR_Sim/src/parameters/high_level_parameters.py
  LDAR_Sim/src/parameters/parameters_holder.py
  LDAR_Sim/src/sensitivity_analysis/__init__.py
  LDAR_Sim/src/sensitivity_analysis/parameter_variator.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_outputs.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_results_manager.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_summary_outputs.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_analysis_visualizations.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_processing.py
  LDAR_Sim/src/sensitivity_analysis/sensitivity_visualization_helpers.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_parameter_variator/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_parameter_variator/test_vary_parameter_values.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_analysis_outputs.py/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_analysis_outputs.py/test_gen_true_vs_est_emissions_sens.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_analysis_results_manager/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_analysis_results_manager/test_save_sensitivity_variations_mapping.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_processing/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_processing/test_get_sensitivity_info.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_processing/test_process_parameter_variations.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_processing/test_unpack_parameter_variations.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_visualization_helpers/__init__.py
  LDAR_Sim/testing/unit_testing/test_sensitivity_analysis/test_sensitivity_visualization_helpers/test_extract_sensitivity_data.py
  LDAR_Sim/testing/unit_testing/test_virtual_world/test_sites/test_activate_emissions.py
Labels: enhancement
